name: 'Issue Helper Access'

on:
  workflow_dispatch:
    inputs:
      operation:
        type: choice
        description: Issue Action
        options:
        - 'Issue - Open'
        - 'Issue - Close'
        - 'Issue - Thread - Lock'
        - 'Issue - Thread - Unlock'
        - 'Issue - Comment - Delete'
        - 'Issue - OpenUnlock'
        - 'Issue - CloseLock'
      item_id:
        description: 'Item ID'
        required: true

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Misc Issue Items - https://github.com/actions-cool/issues-helper
  issue_open_unlock1:
    name: Issue - OpenUnlock1
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Issue - OpenUnlock'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Invalid,Resolved,Duplicate,Not-Planned,Incomplete,Known-Issue'

  issue_open_unlock2:
    name: Issue - OpenUnlock2
    needs: [issue_open_unlock1]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'open-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}

  issue_open_unlock3:
    name: Issue - OpenUnlock3
    needs: [issue_open_unlock2]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'unlock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}

  # Misc Issue Items - https://github.com/actions-cool/issues-helper
  issue_close_lock1:
    name: Issue - CloseLock1
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Issue - CloseLock'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'remove-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
          labels: 'Queries,Triage,Tagged,Stale'

  issue_close_lock2:
    name: Issue - CloseLock2
    needs: [issue_close_lock1]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}

  issue_close_lock3:
    name: Issue - CloseLock3
    needs: [issue_close_lock2]
    runs-on: ubuntu-20.04

    if: ${{ success() || failure() }}
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'lock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}

  # Misc Issue Items - https://github.com/actions-cool/issues-helper
  issue_open:
    name: Issue - Open
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Issue - Open'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'open-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}

  issue_close:
    name: Issue - Close
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Issue - Close'
    steps:
      - id: tag_issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'Tagged'

      - id: close_issue
        uses: actions-cool/issues-helper@v3
        with:
          close-reason: 'completed'
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}

  issue_comment_delete:
    name: Issue - Comment - Delete
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Issue - Comment - Delete'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'delete-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.inputs.item_id }}

  issue_thread_lock:
    name: Issue - Thread - Lock
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Issue - Thread - Lock'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'lock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}

  issue_thread_unlock:
    name: Issue - Thread - Unlock
    runs-on: ubuntu-20.04

    if: github.event.inputs.operation == 'Issue - Thread - Unlock'
    steps:
      - uses: actions-cool/issues-helper@v3
        with:
          actions: 'unlock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.inputs.item_id }}
