name: 'Issues Close'

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: 'Job ID'
        required: true
        default: 'all'
  schedule:
    - cron: '6 6 */6 * *'

permissions:
  issues: write

concurrency:
  group: lock

jobs:

  # Handle Stale Threads - https://github.com/actions/stale
  stale:
    name: Flag or Close Issues
    runs-on: ubuntu-20.04

    if: github.event_name == 'schedule' || github.event.inputs.job_id == 'all' || github.event.inputs.job_id == 'stale'
    steps:

      - name: Handle Cancelled/Duplicate/Invalid/Wierd/Not-Planned Issues
        uses: actions/stale@v7
        with:
          ignore-issue-updates: true
          close-issue-reason: 'completed'
          close-issue-message: ''
          days-before-stale: 0
          days-before-close: 1
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          any-of-labels: 'Cancelled, Duplicate, Known-Issue, Invalid, Cannot-Replicate, Not-Planned'
          remove-issue-stale-when-updated: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inter-Step-Pause
        run: |
          sleep 15s

      - name: Handle Incomplete Issues
        uses: actions/stale@v7
        with:
          close-issue-reason: 'completed'
          stale-issue-message: >
            This item is being flagged for closure due to missing required information.
          close-issue-message: >
            This item is being closed due to missing required information.
          days-before-stale: 0
          days-before-close: 3
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          any-of-labels: 'Incomplete'
          remove-issue-stale-when-updated: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inter-Step-Pause
        run: |
          sleep 15s

      - name: Handle Resolved Issues
        uses: actions/stale@v7
        with:
          ignore-issue-updates: true
          close-issue-reason: 'completed'
          stale-issue-message: ''
          close-issue-message: ''
          days-before-stale: 0
          days-before-close: 1
          exempt-assignees: ''
          stale-issue-label: 'Tagged'
          any-of-labels: 'Resolved'
          remove-issue-stale-when-updated: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inter-Step-Pause
        run: |
          sleep 15s

      - name: Handle No-Response Issues
        uses: actions/stale@v7
        with:
          close-issue-reason: 'completed'
          stale-issue-message: |-
            Dear @${{ github.event.issue.user.login }},

            This item is being flagged for closure due to a lack of response.
          close-issue-message: |-
            Dear @${{ github.event.issue.user.login }},

            This item is being closed due to a lack of response.
          days-before-stale: 2
          days-before-close: 3
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Stale'
          any-of-labels: 'Queries'
          remove-issue-stale-when-updated: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Inter-Step-Pause
        run: |
          sleep 15s

      - name: Catchall Closer
        uses: actions/stale@v7
        with:
          close-issue-reason: 'completed'
          stale-issue-message: >
            This item is being flagged for closure due to inactivity.
          close-issue-message: >
            This item is being closed due to inactivity.
          days-before-stale: 30
          days-before-close: 30
          exempt-assignees: 'dakanji'
          stale-issue-label: 'Tagged'
          exempt-issue-labels: 'Cancelled, Duplicate, Known-Issue, Invalid, Cannot-Replicate, Not-Planned, Resolved, Queries, Incomplete'
          remove-issue-stale-when-updated: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
