
name: 'Auto Labels'

on:
  workflow_dispatch:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled]

permissions:
  contents: read
  issues: write

jobs:

  # Auto Labels - https://github.com/dessant/label-actions
  auto_labels:
    name: Handle Labels
    runs-on: ubuntu-20.04

    if: github.actor == 'dakanji'
    steps:
      - uses: dessant/label-actions@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: '.github/label-config.yml'
          process-only: ''

  # Check Labels - https://github.com/mheap/github-action-required-labels
  handle_enhance_check:
    name: Handle Enhance - Check
    needs: [auto_labels]
    runs-on: ubuntu-20.04

    if: ${{ always() && github.actor == 'dakanji' && (github.event.label.name == 'Invalid' || github.event.label.name == 'Not-Planned') }}
    outputs:
      status: ${{ steps.handle_enhance_check_main.outputs.status }}
    steps:
      - id: handle_enhance_check_main
        uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "Enhancement"
          exit_type: success

  # Close Issue - https://github.com/actions-cool/issues-helper
  handle_enhance_act:
    name: Handle Enhance - Act
    needs: [handle_enhance_check]
    runs-on: ubuntu-20.04

    if: needs.handle_enhance_check.outputs.status == 'success'
    steps:

      - name: Tag Item
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'Tagged'

      - name: Close Item
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
